a = float(input("Enter the value of a:"))
b = float(input("Enter the value of b:"))
print("The sum of",a,"and",b,"is",a+b)
print("The sum of {0:.4f} and {1:.4f} is {2:.4f}".format(a,b,a+b))
print(f"The sum of {a} and {b} is {a+b}")
print("Sum till five places is {0:.4f}".format(a+b))
